config/routes.rb
Prelaunchr::Application.routes.draw do

  mount Buttercms::Engine => '/blog'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "users#new"

  resources :users, path: '' do
    member do
    end
    collection do
      get 'unsubscribe_mail'
      post 'create'
      get 'refer', path: 'refer-a-friend'
      put 'clear_email_in_cookie'
      get 'check_if_user_exists'
      get 'terms_and_conditions'
    end
  end


  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'users#redirect', :format => false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    belongs_to :referrer, :class_name => "User", :foreign_key => "referrer_id"
    has_many :referrals, :class_name => "User", :foreign_key => "referrer_id"

    validates :email, :uniqueness => true, :format => { :with => /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/i, :message => "Invalid email format." }
    validates :referral_code, :uniqueness => true
    validates :selected_place, length: {maximum: 255}
    before_save :accept_terms

    before_create :create_referral_code
    after_create :send_welcome_email
    # , :subscribe_to_mailchimp
    after_create :send_referral_alert, :if => lambda {|u| u.has_referral }
    after_create :update_referrals_count, :if => lambda {|u| u.referrer }

    REFERRAL_STEPS = [
        {
            'count' => 5,
            "html" => "TOLC Lube 50ml",
            "class" => "two",
        },
        {
            'count' => 10,
            "html" => "TOLC Lube 50ml<br>+ Condoms",
            "class" => "three",
        },
        {
            'count' => 15,
            "html" => "TOLC lube 100ml",
            "class" => "four",
        },
        {
            'count' => 20,
            "html" => "TOLC lube 100ml<br>+ Mystery Sex Toy",
            "class" => "five",
        }
    ]

    def has_referral
        referrer_id && referrer.check_subscription
    end

    def check_subscription
        !unsubscribe_mail
    end

    def create_email_token
        token = Digest::MD5.new
        hex = SecureRandom.hex(5)
        token << self.email + hex + Integer(Time.now).to_s
        self.update(email_token: token)
        yield
    end

    def send_welcome_email
        self.create_email_token do
            mail = Notifier.signup_email(self)
            mail.deliver_now
        end
    end

    private

    def create_referral_code
        referral_code = SecureRandom.hex(5)
        @collision = User.find_by_referral_code(referral_code)

        while !@collision.nil?
            referral_code = SecureRandom.hex(5)
            @collision = User.find_by_referral_code(referral_code)
        end

        self.referral_code = referral_code
    end

    def send_referral_alert
        self.referrer.create_email_token do
            mail = Notifier.referral_alert(self.referrer)
            mail.deliver_now
        end
    end

    # def subscribe_to_mailchimp
    #     MailChimp.new().subscribe(self)
    # end

    def update_referrals_count
        user = referrer
        count = referrer.referrals.count
        user.update(referrals_count: count)
        # MailChimp.new().update_referrals(self.referrer)
    end

    def accept_terms
        self.terms_accepted = selected_place.present?
        true
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_filter :skip_first_page, :only => :new

    def new
        @bodyId = 'home'
        @is_mobile = mobile_device?
        if cookies[:email_clear]
            gon.email_clear = true
            cookies.delete :email_clear
        end

        @user = User.new

        respond_to do |format|
            format.html
        end
    end

    def create
        # Get user to see if they have already signed up
        @user = User.find_by_email(user_params[:email]);
            
        # If user doesnt exist, make them, and attach referrer
        if @user.nil?

            cur_ip = IpAddress.find_by_address(request.env['HTTP_X_FORWARDED_FOR'])

            if !cur_ip
                cur_ip = IpAddress.create(
                    :address => request.env['HTTP_X_FORWARDED_FOR'],
                    :count => 0
                )
            end


            cur_ip.count = cur_ip.count + 1
            cur_ip.save
            @user = User.new(user_params)

            @referred_by = User.find_by_referral_code(cookies[:h_ref])

            puts '------------'
            puts @referred_by.email if @referred_by
            puts params[:user][:email].inspect
            puts request.env['HTTP_X_FORWARDED_FOR'].inspect
            puts '------------'

            if @referred_by
                @user.referrer = @referred_by
            end
            if @user.save
                cookies[:h_email] = { :value => @user.email }
                ret = {redirect: true, enter_competition: @user.selected_place.present?}
            else
                ret = {redirect: false, error_fields: @user.errors.messages.keys}
            end
        else
            if !@user.selected_place.present? && user_params[:selected_place].present?
                @user.update(selected_place: user_params[:selected_place])
                # MailChimp.new().update_selected_place(@user)
            end
            cookies[:h_email] = { :value => @user.email }
            unless @user.check_subscription
                @user.update(unsubscribe_mail: false)
                @user.send_welcome_email
                # MailChimp.new().resubscribe(@user.email)
            end
            ret = {redirect: true, enter_competition: @user.selected_place.present?}
        end
        render json: ret
    end

    def refer
        email = cookies[:h_email]

        @bodyId = 'refer'
        @is_mobile = mobile_device?

        @user = User.find_by_email(email)

        respond_to do |format|
            if !@user.nil?
                format.html #refer.html.erb
            else
                format.html { redirect_to root_path, :alert => "Something went wrong!" }
            end
        end
    end

    def unsubscribe_mail
        user = User.find_by_email_token(params[:token]) if params[:token]
        if user
            if user.update(unsubscribe_mail: true)
                cookies.delete :h_email
                # MailChimp.new().unsubscribe(user.email)
            end
        else
            redirect_to root_path
        end
    end

    def redirect
        redirect_to root_path, :status => 404
    end

    def clear_email_in_cookie
        cookies.delete :h_email
        cookies[:email_clear] = {value: true}
        redirect_to '/'
    end

    def check_if_user_exists
        user = User.find_by_email(params[:email])
        render json: {user_exists: user.present?}
    end

    def terms_and_conditions
    end

    private

    def user_params
        params.require(:user).permit(:selected_place, :email)
    end

    def skip_first_page
        if !Rails.application.config.ended
            email = cookies[:h_email]
            if email and !User.find_by_email(email).nil?
                redirect_to '/refer-a-friend'
            else
                cookies.delete :h_email
            end
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def get_class_for_progress
    referrals_count = @user.referrals.count
    class_name =
      if referrals_count >= 50
        'one-year-free-condoms'
      elsif referrals_count >= 20
        'mystery-sex-toy'
      elsif referrals_count >= 10
        'ten-pack-condoms'
      elsif referrals_count >= 5
        'three-pack-condoms'
      elsif referrals_count < 5
        'no-offers'
      end
  end

  def tolc_offers
    [
      {
        friends_count: 5,
        offer: 'Official Entry of<br>Competition'
      },
      {
        friends_count: 10,
        offer: '3 Pack<br>Condoms'
      },
      {
        friends_count: 20,
        # offer: '20 Pack<br>Condoms'
        offer: '10 Pack<br>Condoms'
      },
      {
        friends_count: 50,
        offer: '1 Year Worth of<br>Free Condoms'
      }
    ]
  end

  def get_class_for_offer(index, count)
    index == count -1 ?
      'col-xs-3'
      : 'col-xs-2'
  end

  def get_count_class(count)
    referrals_count = @user.referrals.count
    referrals_count >= count ?
      'reached' : 'not-reached'
  end

  def vertical_offer_margin_top
    ['44px', '35px', '40px', '40px']
  end

  def bar_height
    referrals_count = @user.referrals.count
    if referrals_count >= 50
      '310px'
    elsif referrals_count >= 20
      '220px'
    elsif referrals_count >= 10
      '150px'
    elsif referrals_count >= 5
      '80px'
    elsif referrals_count < 5
      '35px'
    end
  end

  def terms_list
    [
      "This is a game of skill. Chance plays no part in determining the winner. Each entry will be  individually judged, based upon individual creative merit. All entries must be an independent creation by the entrant and free of any claims that they infringe any third party rights. Entries must not have been published previously and/or have been used to win prizes in any other competitions.",
      "Winning entrant will have the right to nominate any music festival in the world to travel to, subject to ticket availability.",
      "Employees of the promoter and agencies associated with this promotion are ineligible to enter the competition, as are their immediate families.",
      "To enter, entrants must have submitted a valid email address and observe and comply with all competition and website terms and conditions.",
      "The judges reserve the right to disqualify any entrant submitting an entry which, in the opinion of the judges, includes objectionable content, including but not limited to profanity, or potentially insulting, scandalous, inflammatory or defamatory comments. The judges' decision will be final and no correspondence will be entered into.",
      "All entries become and remain the property of the promoter and agencies associated with this promotion (Big Richard Industries Pty Ltd).",
      "Winners of the competition must be 18 years old and over and residents of Australia, New Zealand, USA, UK, Canada or Japan.",
      "The promoter reserves the right to withdraw or amend the competition as necessary due to circumstances outside its control.",
      "The prize is non-transferable and non-redeemable for cash. Any attempt to resell or auction all or any part of this prize will result in an immediate cancellation of the prize. Prize cannot be exchanged for another itinerary. In the event that, for any reason whatsoever, a winner does not take an element of the prize at the time stipulated by the promoter then that element of the prize will be forfeited by the winner and cash will not be awarded in lieu of that element of the prize. Both parties must travel together.",
      "The promoter reserves the right to substitute any component of the prize for an itinerary of equal value at their discretion.",
      "Prize cannot be gifted to other persons in lieu of the winner not being able to travel. Should the winner not be able to complete all aspects of the itinerary within the period of prize validity, the remaining items shall be forfeited without any replacement for their value.",
      "The winner is required to obtain the relevant & suitable travel insurance at their own expense in order to be able to take the competition prize. It is the traveller's personal responsibility to ensure that they have valid documentation, including but not limited to,",
      "Valid passports, visas, and health requirements, which meet the requirements of immigration and other government authorities at every destination. Any fines, penalties, payments or expenditures incurred as a result of such documents not meeting the requirements of those authorities will be the sole responsibility of the traveller/s.",
      "Prize includes 2 X tickets to any music festival in the world, 2 X economy flights to nearby region or city where music festival is held and 2 X 2 nights accommodation near to where the chosen music festival is located. Supply of all aspects of prize are at discretion of the promoter. Unless expressly stated, all other expenses become the responsibility of the winner.",
      "Additional prizes such as condoms and other physical goods indicated on the prize page require that valid email addresses of real people (and not an additional email of the entrant) are submitted to Big Richard Industries. Big Richard, as the promoter, reserves the right to validate email addresses to be that of real people through a number of methods including but not limited to email communication and tracking of website visitation.",
      "If the winning entrant also qualifies for additional prizes by referring 5 or more email addresses subject to meeting all other criteria mentioned here, the winning entrant will qualify for $1,000 extra spending money.",
      "The promoter shall not be liable for any loss or damage whatsoever which is suffered (including, but not limited to, indirect or consequential loss) or for personal injury which is suffered or sustained, in connection with the prize, except for any liability which cannot be excluded by laws.",
      "The prize is subject to availability as determined by the promoter. The entry period is valid from June 2016 - Dec 2016.",
      "Promotion commences 16 June 2016. Entries close 5pm December 30 2016.",
      "By entering the competition, all entrants will be deemed to have accepted and agreed to be bound by these rules.",
      "The Promoter is the Big Richard Industries, Birrell St, NSW 2026 ABN 11141540829.",
      "The information you are asked to provide to Big Richard Industries and is personal information and is protected by the Privacy Act 1988. The Gallery will not disclose this information to other parties other than in accordance with the Privacy Act 1988.",
      "All entries become the property of the promoter. The promoter may use any content supplied excluding names for any commercial purpose, including future promotional marketing and publicity purposes. Any and all content will be published in an anonymised format or with first name and age, only.",
      "Independent financial advice should be sought as tax implications may arise as a result of accepting the prize.",
      "In the event that for any reason whatsoever a winner does not accept the prize at the time stipulated by the promoter then the prize will be forfeited by the winner and cash will not be awarded in lieu of the prize.",
      "Entries will be judged at the promoter’s office in a 2 week period following the competition close date. The promoter reserves the right to change the competition close date and will notify entrants in advance of the change.",
      "The winner will be notified in writing by email within thirty (30) working days of the conclusion of the competition.",
      "If the promoter is unable to contact the winner within 30 days of the draw and the promoter has made every effort to contact them with the information provided by the entrant then the promoter will award the prize to another valid entrant.",
      "It is a condition of entry into this competition that entrants agree to receive electronic communication from the promoter."
    ]
  end

end

app/views/users/_ads.html.slim
.row
  .col-xs-12.sustainable-rubber-part.ads
    .row
      .col-xs-6.col-sm-5.col-sm-offset-1.text-center
        .row
          .image
            img src=asset_path('refer/desktop/foil_mockup.png')
      .col-xs-6.col-sm-5
        .row
          .col-sm-8.col-sm-offset-2.col-xs-12
            hr.red-line.pull-left
          .clearfix
          .col-sm-8.col-sm-offset-2.col-xs-12.article
            .heading BIG RICHARD USES SUSTAINABLE RUBBER
            .description All Big Richard condoms are made from sustainable rubber tree plantations. Enjoy a more sustainable sex life with Big Richard.
.row
  .col-xs-12.chemical-free-part.ads
    .row
      .col-xs-6.col-sm-5.col-sm-offset-1#block-1
        .row
          .col-sm-8.col-sm-offset-2.col-xs-12
            hr.red-line.pull-left
          .clearfix
          .col-sm-8.col-sm-offset-2.col-xs-12
            .heading OUR CONDOMS ARE CHEMICAL FREE
            .description All Big Richard Condoms are free from Glycerin and Parabens. Nasty chemicals that are very unsexy. They are also 100% electronically tested, CE and ISO 4074:2002 approved, making them ultra safe.
      .col-xs-5.col-xs-offset-1.col-sm-5.col-sm-offset-0#block-2
        .row
          .image
            img src=asset_path('refer/desktop/Packaging_mockup.png')

app/views/users/_form.html.slim
.row.form-part.text-center
  .col-xs-12.form-content
    .row
      .col-xs-12
        .form-header
          | ENTER BELOW TO WIN
      .col-xs-12
        .form-description
          | We are all about big experiences, so to celebrate our launch we are giving you the chance to try our very first condoms and a win a trip for two to any music festival in the world in 2017 - Coachella, Glastonbury, Lollapalooza, Splendour in the Grass... you name it, we’ll take you there. Fill in your answers below to enter.
      .col-xs-12
        = form_tag check_if_user_exists_users_path, method: :get, remote: true, authenticity_token: false, class: 'sign-up-form' do |f|
          .row
            .col-xs-12
              = text_field_tag :email, '', placeholder: 'Email Address...', class: 'form-control input-box', required: true, type: 'email'
            .clearfix
            .col-xs-12
              .invalid-message-area
                .invalid-email.invalid-message.hide
                  | Please enter a valid email address.
            .clearfix
            .col-xs-12
              = text_area_tag :selected_place, '', placeholder: 'In less then 25 words, tell us the festival of your choice and why we should choose you…', class: 'form-control input-box', required: true, maxlength: '255'
            .clearfix
            .col-xs-12
              .invalid-message-area
                .invalid-selected_place.invalid-message.hide
                  | Please decrease the words.
            .col-xs-12.terms-text
              span By entering the competition you hereby accept the
              a href="/terms_and_conditions" class='conditions'
                span.terms-and-conditions-text &nbsp;terms and conditions.
            .clearfix
            .form-buttons
              = submit_tag '', class: 'hide', id: 'submit_form'
              .btn.sign-up-button.pull-left onclick="$('form.sign-up-form #submit_form').click()"
                | ENTER
              .clearfix
              .or-option
                span.pull-left.white-line
                | or
                span.pull-right.white-line
              a.condoms-only href='#'
               | I just want Big Richard condoms
              a.festival-prize.hide href='#'
                span.back-icon
                span.festival-prize-text I want to win the festival prize
        = form_for @user, html: {class: 'actual-form hide', remote: true} do |f|
          .row
            .col-xs-12
              = f.hidden_field :selected_place, value: ''
            .clearfix
            .col-xs-12
              = f.hidden_field :email, value: ''
            .buttons
              = f.submit '', id: 'create_user_button'
.row
  .form-border
    .grey-line

app/views/users/_header.html.slim
.row.desktop-header
  .col-sm-3.col-xs-4
    = link_to '/' do
      = image_tag asset_path('layout/Logo@2x.png'), class: 'bigrichard-logo'
  .col-sm-6.col-xs-4
  .col-sm-3.col-xs-4.social-links
    .pull-right
      a href="https://www.instagram.com/bigrichardHQ/" class="instagram" target='_blank'
      a href="https://www.facebook.com/bigrichard/" class="facebook" target='_blank'
      a href="https://twitter.com/bigrichardhq" class="twitter" target='_blank'

app/views/users/new.html.slim
- content_for :title, 'Big Richard Condoms'
.fullscreen.background style="background-image:url(#{asset_path('splash/desktop/Page-1-header-image.jpg')});" data-img-width="2048" data-img-height="1249"
  .row.celebration-part
    .col-xs-12.header-logo
      .row.desktop-header
        .col-sm-3.col-xs-4
          = image_tag asset_path('layout/Logo@2x.png'), class: 'bigrichard-logo'
        .col-sm-6.col-xs-4
        .col-sm-3.col-xs-4.social-links
          .pull-right
            a href="https://www.instagram.com/bigrichardHQ/" class="instagram" target='_blank'
            a href="https://www.facebook.com/bigrichard/" class="facebook" target='_blank'
            a href="https://twitter.com/bigrichardhq" class="twitter" target='_blank'
    .col-xs-12.middle-content.hide
      .row
        .col-xs-12.text-center
          .header-text
            | BIG RICHARD IS COMING... TO CELEBRATE, WE’RE FLYING YOU TO ANY MUSIC FESTIVAL IN THE WORLD.
        .clearfix
        .col-xs-12.text-center
          .send-text
            | Seriously.. we’ll take you anywhere you want, and because we love you, we’ll give you the chance to try our very first condoms.
        .clearfix
        .col-xs-12.text-center
          btn.btn.take-me-button
            | TAKE ME THERE
.container-fluid
  .row.content-body.splash-page
    .main-content.col-xs-12
      = render partial: 'ads'
      = render partial: 'form'

app/views/users/refer.html.slim
- content_for :title, 'Win More Prizes'
.container-fluid
  .row.content-body.refer-page
    .col-xs-12.text-center#facebook-like-div.active
      .pop-up-image
        .pull-right
          = image_tag asset_path('refer/desktop/cancel_icon.png'), class: 'pop-up-cancel'
      .fb-page data-href="https://www.facebook.com/bigrichard" data-small-header="true" data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="false"
        blockquote cite="https://www.facebook.com/bigrichard" class="fb-xfbml-parse-ignore"
          a href="https://www.facebook.com/bigrichard"
            | Big Richard
    .main-content.col-xs-12
      .row.refer-part.text-center
        .col-xs-12.header-logo
          .row.desktop-header
            .col-xs-3
              = image_tag asset_path('layout/Logo@2x.png'), class: 'bigrichard-logo'
            .col-xs-6.condom-text
              | YOU HAVE SUCCESSFULLY PASSED THE FIRST STEP
            .col-xs-3.social-links
              .pull-right
                a href="https://www.instagram.com/bigrichardHQ/" class="instagram" target='_blank'
                a href="https://www.facebook.com/bigrichard/" class="facebook" target='_blank'
                a href="https://twitter.com/bigrichardhq" class="twitter" target='_blank'
        .col-xs-12.header-text
          / | WIN MORE PRIZES
          | YOU'RE NEARLY THERE..
        .col-xs-12
          .share-text
            / | Share your unique link via email, Facebook or Twitter to score free Big Richard condom packs and $1,000 spending money if you're the festival prize winner.
            | Share your unique link below with your friends.
            br
            span.bold-text
              | If 5 friends sign up - you're in the running.
            span
              | &nbsp;Goodluck!
        .col-xs-12
          .link-share
            - referral_url = "#{root_url}?ref=#{@user.referral_code}"
            .link-box
              = text_field_tag :referral_code, referral_url, class: 'refer-link-box text-center'
            - url = "#{root_url}?ref=#{@user.referral_code}"
            .social
              <a href="mailto:?Subject=Big Richard is coming!&amp;Body=Hi%20Friends!%0D%0A%0D%0A%0D%0ABig%20Richard%20is%20coming%20soon%E2%80%A6%20and%20to%20celebrate%2C%20they%20are%20giving%20away%20free%20condoms%20and%20flying%202%20people%20to%20any%20music%20festival%20in%20the%20world.%0D%0A%0D%0A%0D%0AClick%20the%20link%20below%20and%20you%20too%20could%20be%20a%20winner.%0D%0A%0D%0A#{url}" class='mail-share'>
                .share-ma
              </a>
              a.twitter-share href="http://twitter.com/share?url=#{url}&text=Scored+a+chance+to+fly+to+any+music+festival+in+the+world+on+@bigrichardhq.+FREE+condoms+here!&hashtags=BIGRICHARD,FREEBIE" target="_blank"
                .share-tw
              a.facebook-share href="http://www.facebook.com/sharer.php?u=#{url}&title=BIG RICHARD IS FLYING YOU TO ANY MUSIC FESTIVAL IN THE WORLD" target="_blank"
                .share-fb
        .col-xs-12
          = image_tag asset_path('refer/desktop/DownArrow@2x.png'), class: 'down-arrow'
      .row.offer-part.text-center
        .bonus
          | BONUS
        .col-xs-12.explanation
          / | HERE'S HOW IT WORKS:
          | A CHANCE TO WIN MORE PRIZES
        .col-xs-12.win-money
          / | Win $1000 spending money if you reach any prize level.
          | Here's how it works:
        .col-xs-12
          .row.friends
            .col-sm-1
            .col-sm-2.col-xs-3.offer-heading
              | FRIENDS JOINED
            - friends_count = tolc_offers.map{|o| o[:friends_count]}
            - friends_count.each_with_index do |count, i|
              .col-sm-2 class=get_class_for_offer(i, friends_count.count)
                .no-of-friends class=get_count_class(count)
                  = count
        .col-xs-12
          .row
            .col-sm-1
            .col-sm-10.col-xs-12
              .progressbar
                .row
                  .col-xs-12
                    .progress class=get_class_for_progress
        .col-xs-12
          .row.rewards
            .col-sm-1
            .col-sm-2.col-xs-3.offer-heading
              | REWARDS
            - offers = tolc_offers.map{|o| o[:offer]}
            - offers.each_with_index do |offer, i|
              .col-sm-2 class=get_class_for_offer(i, offers.count)
                .offer
                  = offer.html_safe
      .row
        .col-xs-12.junk-mail-message.text-center
          | Check your junk mail if you haven’t recieved an email yet.
      .row
        .col-xs-12.text-center
          / = link_to 'Click here if you wish to signup as a different email user.', clear_email_in_cookie_users_path, class: 'new-signup', method: :put
          = link_to 'SIGN UP AS DIFFERENT USER', clear_email_in_cookie_users_path, class: 'new-signup', method: :put
      = render partial: 'ads'

app/views/users/terms_and_conditions.html.slim
- content_for :title, 'Big Richard | Terms and Conditions'
.container-fluid
  - className = mobile_device? ? 'terms-and-conditions-mobile' : ''
  .row.content-body.terms-and-conditions class=className
    .main-content.col-xs-12
      .row
        .col-xs-12.header-logo
          = render partial: 'header'
        .col-xs-12.terms-lists
          .row
            .col-sm-offset-1.col-sm-10.col-xs-12
              .row
                .col-xs-12.header-text
                  | BIG RICHARD INDUSTRIES MUSIC FESTIVAL LAUNCH COMPETITION
                .col-xs-12.terms-header
                  | TERMS AND CONDITIONS
                .col-xs-12.lists
                  table
                    thead
                    tbody
                      - terms_list.each_with_index do |term, index|
                        tr
                          td.sn
                            = "#{index + 1}."
                          td.term
                            = term
                        tr.gap

app/views/users/unsubscribe_mail.html.slim
.container-fluid
  .row.content-body.unsubscribed-page
    .main-content.col-xs-12.text-center
      .row.main-logo
        .col-xs-12
          = image_tag asset_path('Big-Richard-logo-(2x).png'), class: 'bigrichard-logo'
      .row
        .col-xs-12.header-text
          | UNSUBSCRIBE SUCCESSFUL
      .row.removed-text
        .col-xs-12
          | You have been removed from our email list.
      .row.return-text
        .col-xs-12
          = link_to 'return to our website', '/'